services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - gotodoapp-network

networks:
    gotodoapp-network:
        driver: bridge